In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("profiles.csv",sep=",")

In [4]:
df.head(10)

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,leadership_style
0,5,4,1,5,5,5,1,3,5,5,...,2,2,2,1,3,1,2,5,4,Pacesetting
1,4,2,4,3,3,5,5,2,3,2,...,3,2,1,5,3,1,2,3,2,Delegative
2,2,2,3,2,3,1,3,4,1,5,...,5,5,1,2,3,4,4,4,2,Delegative
3,2,1,4,1,2,2,5,5,1,5,...,5,1,1,2,1,2,2,1,4,Authoritarian
4,5,4,5,3,4,1,1,4,5,1,...,1,2,3,4,3,4,1,5,3,Delegative
5,2,3,2,4,5,4,5,5,2,4,...,5,4,2,3,4,4,5,4,4,Transformational
6,2,2,5,1,4,3,5,1,1,5,...,4,4,1,2,4,2,4,5,4,Transactional
7,3,2,1,1,3,5,2,5,1,3,...,1,4,4,3,2,4,3,1,3,Transactional
8,4,4,2,5,2,1,3,5,5,5,...,5,1,4,2,5,5,3,4,4,Participative
9,4,1,1,2,3,1,2,1,3,3,...,2,2,5,4,1,4,1,3,3,Delegative

In [5]:
df.shape

(20009, 27)

In [9]:
df.Q1.duplicated().sum()

np.int64(20004)

In [10]:
df.Q2.duplicated().sum()

np.int64(20004)

In [11]:
df.loc[df.Q1.duplicated(),:]

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,leadership_style
3,2,1,4,1,2,2,5,5,1,5,...,5,1,1,2,1,2,2,1,4,Authoritarian
4,5,4,5,3,4,1,1,4,5,1,...,1,2,3,4,3,4,1,5,3,Delegative
5,2,3,2,4,5,4,5,5,2,4,...,5,4,2,3,4,4,5,4,4,Transformational
6,2,2,5,1,4,3,5,1,1,5,...,4,4,1,2,4,2,4,5,4,Transactional
8,4,4,2,5,2,1,3,5,5,5,...,5,1,4,2,5,5,3,4,4,Participative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20004,3,3,1,2,3,3,1,5,5,3,...,2,3,5,5,4,5,1,3,5,Participative
20005,2,2,4,5,4,2,5,2,2,2,...,1,2,2,4,4,3,4,2,3,Delegative
20006,4,1,3,2,5,4,2,2,5,5,...,4,1,1,3,2,5,2,1,1,Visionary
20007,5,4,4,1,3,2,5,5,5,3,...,3,4,3,2,2,3,3,3,5,Visionary
20008,5,3,5,2,1,5,1,5,1,3,...,5,4,3,2,1,3,2,4,3,Pacesetting

In [12]:
df.loc[df.Q2.duplicated(),:]

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,leadership_style
2,2,2,3,2,3,1,3,4,1,5,...,5,5,1,2,3,4,4,4,2,Delegative
4,5,4,5,3,4,1,1,4,5,1,...,1,2,3,4,3,4,1,5,3,Delegative
6,2,2,5,1,4,3,5,1,1,5,...,4,4,1,2,4,2,4,5,4,Transactional
7,3,2,1,1,3,5,2,5,1,3,...,1,4,4,3,2,4,3,1,3,Transactional
8,4,4,2,5,2,1,3,5,5,5,...,5,1,4,2,5,5,3,4,4,Participative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20004,3,3,1,2,3,3,1,5,5,3,...,2,3,5,5,4,5,1,3,5,Participative
20005,2,2,4,5,4,2,5,2,2,2,...,1,2,2,4,4,3,4,2,3,Delegative
20006,4,1,3,2,5,4,2,2,5,5,...,4,1,1,3,2,5,2,1,1,Visionary
20007,5,4,4,1,3,2,5,5,5,3,...,3,4,3,2,2,3,3,3,5,Visionary
20008,5,3,5,2,1,5,1,5,1,3,...,5,4,3,2,1,3,2,4,3,Pacesetting

In [16]:
clean_df = df.drop_duplicates(keep=False)
clean_df.to_csv('cleaned_data.csv', index=False)